load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "roles",
    srcs = [
        "roles.go",
    ],
    importpath = "aifo.dev/aifo/slideinsight/internal/server/routes/roles",
    visibility = ["//aifo/slideinsight:__subpackages__"],
    deps = [
        "//aifo/slideinsight/internal/config",
        "//aifo/slideinsight/internal/server/handlers",
        "//aifo/slideinsight/internal/server/middleware",
        "//aifo/slideinsight/internal/server/services",
        "@com_github_gofiber_fiber_v2//:fiber",
    ],
)
