load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "slides",
    srcs = [
        "common_props.go",
        "factory.go",
        "openslide_adapter.go",
        "slide.go",
        "tiff_adapter.go",
        "xyz.go",
    ],
    importpath = "aifo.dev/aifo/slidescope/internal/slides",
    visibility = ["//visibility:public"],
    deps = [
        "//aifo/openslide_go/openslide",
        "//aifo/slidescope/internal/tiff",
        "@org_golang_x_image//draw",
    ],
)

go_test(
    name = "slides_adapter_test",
    srcs = [
        "adapter_integration_test.go",
        "adapter_test.go",
    ],
    embed = [":slides"],
    deps = [
        "//aifo/openslide_go/openslide",
        "//aifo/slidescope/internal/tiff",
    ],
)

go_test(
    name = "slides_tile_pyramid_test",
    srcs = [
        "xyz_test.go",
    ],
    embed = [":slides"],
)

go_test(
    name = "slides_factory_test",
    srcs = [
        "factory_test.go",
    ],
    embed = [":slides"],
    deps = [
        "//aifo/openslide_go/openslide",
        "//aifo/slidescope/internal/tiff",
    ],
)
