load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "middleware",
    srcs = [
        "auth.go",
        "errors.go",
    ],
    importpath = "aifo.dev/aifo/slidescope/internal/server/middleware",
    visibility = ["//visibility:public"],
    deps = [
        "//aifo/slidescope/internal/config",
        "//aifo/slidescope/internal/server/domain",
        "//aifo/slidescope/internal/server/errors",
        "@com_github_gofiber_fiber_v2//:fiber",
        "@com_github_golang_jwt_jwt_v5//:jwt",
    ],
)

go_test(
    name = "middleware_test",
    srcs = ["auth_test.go"],
    embed = [":middleware"],
    deps = [
        "//aifo/slidescope/internal/config",
        "@com_github_gofiber_fiber_v2//:fiber",
        "@com_github_golang_jwt_jwt_v5//:jwt",
        "@com_github_stretchr_testify//assert",
    ],
)
