load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "settings",
    srcs = [
        "settings.go",
    ],
    importpath = "aifo.dev/aifo/slideinsight/internal/server/routes/settings",
    visibility = ["//aifo/slideinsight:__subpackages__"],
    deps = [
        "//aifo/slideinsight/internal/server/handlers",
        "//aifo/slideinsight/internal/server/services",
        "@com_github_gofiber_fiber_v2//:fiber",
    ],
)
