load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "algorithms",
    srcs = [
        "adapter.go",
        "crud.go",
        "search.go",
    ],
    importpath = "aifo.dev/aifo/slideinsight/internal/datasources/database/sqlite/algorithms",
    visibility = ["//aifo/slideinsight:__subpackages__"],
    deps = [
        "//aifo/slideinsight/internal/server/domain",
        "//aifo/slideinsight/internal/server/errors",
        "//aifo/slideinsight/internal/utils",
        "@com_github_google_uuid//:uuid",
    ],
)
