load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "handlers",
    srcs = [
        "auth.go",
        "masks.go",
        "slides.go",
        "users.go",
    ],
    importpath = "aifo.dev/aifo/slidescope/internal/server/handlers",
    visibility = ["//visibility:public"],
    deps = [
        "//aifo/slidescope/internal/config",
        "//aifo/slidescope/internal/server/domain",
        "//aifo/slidescope/internal/server/errors",
        "//aifo/slidescope/internal/server/middleware",
        "//aifo/slidescope/internal/server/services",
        "@com_github_gofiber_fiber_v2//:fiber",
    ],
)

go_test(
    name = "handlers_test",
    srcs = [
        "auth_test.go",
        "masks_test.go",
        "slides_test.go",
        "users_test.go",
    ],
    embed = [":handlers"],
    deps = [
        "//aifo/slidescope/internal/config",
        "//aifo/slidescope/internal/datasources/database",
        "//aifo/slidescope/internal/server/domain",
        "//aifo/slidescope/internal/server/errors",
        "//aifo/slidescope/internal/server/middleware",
        "//aifo/slidescope/internal/server/services",
        "@com_github_gofiber_fiber_v2//:fiber",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//mock",
    ],
)

go_test(
    name = "handlers_masks_test",
    srcs = ["masks_test.go"],
    embed = [":handlers"],
    deps = [
        "//aifo/slidescope/internal/server/domain",
        "//aifo/slidescope/internal/server/errors",
        "//aifo/slidescope/internal/server/middleware",
        "//aifo/slidescope/internal/server/services",
        "@com_github_gofiber_fiber_v2//:fiber",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//mock",
    ],
)
