_target_: research.physician_gtv_fingerprint.models.classifier_module.ClassifierLitModule
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.00001
  weight_decay: 0
net:
  _target_: monai.networks.nets.resnet.resnet18
  n_input_channels: 2
  spatial_dims: 3
  num_classes: 10
# compile model for faster training with pytorch 2.0
compile: false
