load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "database",
    srcs = [
        "db.go",
        "db_mock.go",
    ],
    importpath = "aifo.dev/aifo/slideinsight/internal/datasources/database",
    visibility = ["//aifo/slideinsight:__subpackages__"],
    deps = [
        "//aifo/slideinsight/internal/datasources/database/sqlite",
        "//aifo/slideinsight/internal/datasources/database/sqlite/schema",
        "//aifo/slideinsight/internal/server/errors",
        "//aifo/slideinsight/internal/server/ports",
        "//aifo/slideinsight/internal/utils",
        "@com_github_gofiber_fiber_v2//log",
        "@com_github_mattn_go_sqlite3//:go-sqlite3",
        "@com_github_stretchr_testify//mock",
    ],
)
