// Code generated by dicommapper; DO NOT EDIT.
package processor

import (
	"fmt"
	"strconv"

	"github.com/NKI-AI/aiforoncology/src/golang/research/dcmw/internal/models"
	"github.com/suyashkumar/dicom"
	"github.com/suyashkumar/dicom/pkg/tag"
)

func mapDatasetToPatient(dataset *dicom.Dataset) (*models.Patient, error) {
	model := &models.Patient{}

	// Mapping regular DICOM fields
	// Set PatientMRN
	elem, err := dataset.FindElementByTag(tag.Tag{Group: 0x0010, Element: 0x0020})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.PatientMRN = v
			case []string:
				model.PatientMRN = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set PatientName
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0010, Element: 0x0010})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.PatientName = v
			case []string:
				model.PatientName = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set PatientBirthDate
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0010, Element: 0x0030})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.PatientBirthDate = v
			case []string:
				model.PatientBirthDate = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}

	// Handling datetime fields

	return model, nil
}
func mapDatasetToStudy(dataset *dicom.Dataset) (*models.Study, error) {
	model := &models.Study{}

	// Mapping regular DICOM fields
	// Set PatientSex
	elem, err := dataset.FindElementByTag(tag.Tag{Group: 0x0010, Element: 0x0040})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.PatientSex = v
			case []string:
				model.PatientSex = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set PatientWeight
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0010, Element: 0x1030})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.PatientWeight = v
			case []string:
				model.PatientWeight = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set StudyInstanceUID
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0020, Element: 0x000D})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.StudyInstanceUID = v
			case []string:
				model.StudyInstanceUID = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set StudyDescription
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x1030})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.StudyDescription = v
			case []string:
				model.StudyDescription = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set StudyID
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0020, Element: 0x0010})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.StudyID = v
			case []string:
				model.StudyID = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set StudyDate
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x0020})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.StudyDate = v
			case []string:
				model.StudyDate = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set StudyTime
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x0030})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.StudyTime = v
			case []string:
				model.StudyTime = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set AccessionNumber
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x0050})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.AccessionNumber = v
			case []string:
				model.AccessionNumber = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}

	// Handling datetime fields
	// Combine StudyDate and StudyTime into StudyDateTime
	if model.StudyDate != "" && model.StudyTime != "" {
		dateTime, err := parseDICOMDateTime(&model.StudyDate, &model.StudyTime)
		if err != nil {
			return nil, fmt.Errorf("failed to parse datetime for StudyDateTime: %v", err)
		}
		model.StudyDateTime = dateTime
	}

	return model, nil
}
func mapDatasetToSeries(dataset *dicom.Dataset) (*models.Series, error) {
	model := &models.Series{}

	// Mapping regular DICOM fields
	// Set SeriesInstanceUID
	elem, err := dataset.FindElementByTag(tag.Tag{Group: 0x0020, Element: 0x000E})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.SeriesInstanceUID = v
			case []string:
				model.SeriesInstanceUID = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set SeriesNumber
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0020, Element: 0x0011})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.SeriesNumber = v
			case []string:
				model.SeriesNumber = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set SeriesDescription
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x103E})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.SeriesDescription = v
			case []string:
				model.SeriesDescription = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set Modality
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x0060})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.Modality = v
			case []string:
				model.Modality = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set ProtocolName
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x1030})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.ProtocolName = v
			case []string:
				model.ProtocolName = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set BodyPartExamined
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0015})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.BodyPartExamined = v
			case []string:
				model.BodyPartExamined = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set ContrastBolusAgent
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0010})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.ContrastBolusAgent = v
			case []string:
				model.ContrastBolusAgent = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set FrameOfReferenceUID
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0020, Element: 0x0052})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.FrameOfReferenceUID = v
			case []string:
				model.FrameOfReferenceUID = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set PlanarConfiguration
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0028, Element: 0x0006})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.PlanarConfiguration = v
			case []string:
				model.PlanarConfiguration = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set PatientPosition
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x5100})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.PatientPosition = v
			case []string:
				model.PatientPosition = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set InstitutionName
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x0080})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.InstitutionName = v
			case []string:
				model.InstitutionName = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set InstanceCount
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0020, Element: 0x1209})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedInt, err := strconv.Atoi(v)
				if err == nil {
					model.InstanceCount = parsedInt
				}
			case []string:
				parsedInt, err := strconv.Atoi(v[0])
				if err == nil {
					model.InstanceCount = parsedInt
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set AcquisitionDuration
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x9073})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.AcquisitionDuration = v
			case []string:
				model.AcquisitionDuration = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set Manufacturer
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x0070})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.Manufacturer = v
			case []string:
				model.Manufacturer = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set ManufacturerModelName
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x1090})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.ManufacturerModelName = v
			case []string:
				model.ManufacturerModelName = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set SeriesDate
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x0021})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.SeriesDate = v
			case []string:
				model.SeriesDate = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set SeriesTime
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x0031})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.SeriesTime = v
			case []string:
				model.SeriesTime = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set SliceThickness
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0050})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.SliceThickness = v
			case []string:
				model.SliceThickness = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set StudyInstanceUID
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0020, Element: 0x000D})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.StudyInstanceUID = v
			case []string:
				model.StudyInstanceUID = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}

	// Handling datetime fields
	// Combine SeriesDate and SeriesTime into SeriesDateTime
	if model.SeriesDate != "" && model.SeriesTime != "" {
		dateTime, err := parseDICOMDateTime(&model.SeriesDate, &model.SeriesTime)
		if err != nil {
			return nil, fmt.Errorf("failed to parse datetime for SeriesDateTime: %v", err)
		}
		model.SeriesDateTime = dateTime
	}

	return model, nil
}
func mapDatasetToInstance(dataset *dicom.Dataset) (*models.Instance, error) {
	model := &models.Instance{}

	// Mapping regular DICOM fields
	// Set Columns
	elem, err := dataset.FindElementByTag(tag.Tag{Group: 0x0028, Element: 0x0011})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedInt, err := strconv.Atoi(v)
				if err == nil {
					model.Columns = parsedInt
				}
			case []string:
				parsedInt, err := strconv.Atoi(v[0])
				if err == nil {
					model.Columns = parsedInt
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set ContentDate
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x0023})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.ContentDate = v
			case []string:
				model.ContentDate = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set ContentTime
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x0033})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.ContentTime = v
			case []string:
				model.ContentTime = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set SOPInstanceUID
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x0018})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.SOPInstanceUID = v
			case []string:
				model.SOPInstanceUID = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set SOPClassUID
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x0016})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.SOPClassUID = v
			case []string:
				model.SOPClassUID = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set AcquisitionNumber
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0020, Element: 0x0012})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedInt, err := strconv.Atoi(v)
				if err == nil {
					model.AcquisitionNumber = parsedInt
				}
			case []string:
				parsedInt, err := strconv.Atoi(v[0])
				if err == nil {
					model.AcquisitionNumber = parsedInt
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set InstanceNumber
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0020, Element: 0x0013})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedInt, err := strconv.Atoi(v)
				if err == nil {
					model.InstanceNumber = parsedInt
				}
			case []string:
				parsedInt, err := strconv.Atoi(v[0])
				if err == nil {
					model.InstanceNumber = parsedInt
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set Rows
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0028, Element: 0x0010})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedInt, err := strconv.Atoi(v)
				if err == nil {
					model.Rows = parsedInt
				}
			case []string:
				parsedInt, err := strconv.Atoi(v[0])
				if err == nil {
					model.Rows = parsedInt
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set SliceLocation
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0020, Element: 0x1041})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.SliceLocation = v
			case []string:
				model.SliceLocation = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set AcquistionDate
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x0022})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.AcquistionDate = v
			case []string:
				model.AcquistionDate = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set AcquisitionTime
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x0032})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.AcquisitionTime = v
			case []string:
				model.AcquisitionTime = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set InstanceCreationDate
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x0012})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.InstanceCreationDate = v
			case []string:
				model.InstanceCreationDate = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set InstanceCreationTime
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x0013})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.InstanceCreationTime = v
			case []string:
				model.InstanceCreationTime = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set Modality
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x0060})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.Modality = v
			case []string:
				model.Modality = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set SeriesInstanceUID
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0020, Element: 0x000E})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.SeriesInstanceUID = v
			case []string:
				model.SeriesInstanceUID = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}

	// Handling datetime fields
	// Combine ContentDate and ContentTime into ContentDateTime
	if model.ContentDate != "" && model.ContentTime != "" {
		dateTime, err := parseDICOMDateTime(&model.ContentDate, &model.ContentTime)
		if err != nil {
			return nil, fmt.Errorf("failed to parse datetime for ContentDateTime: %v", err)
		}
		model.ContentDateTime = dateTime
	}
	// Combine AcquistionDate and AcquisitionTime into AcquisitionDateTime
	if model.AcquistionDate != "" && model.AcquisitionTime != "" {
		dateTime, err := parseDICOMDateTime(&model.AcquistionDate, &model.AcquisitionTime)
		if err != nil {
			return nil, fmt.Errorf("failed to parse datetime for AcquisitionDateTime: %v", err)
		}
		model.AcquisitionDateTime = dateTime
	}
	// Combine InstanceCreationDate and InstanceCreationTime into InstanceCreationDateTime
	if model.InstanceCreationDate != "" && model.InstanceCreationTime != "" {
		dateTime, err := parseDICOMDateTime(&model.InstanceCreationDate, &model.InstanceCreationTime)
		if err != nil {
			return nil, fmt.Errorf("failed to parse datetime for InstanceCreationDateTime: %v", err)
		}
		model.InstanceCreationDateTime = dateTime
	}

	return model, nil
}
func mapDatasetToMRISpecifics(dataset *dicom.Dataset) (*models.MRISpecifics, error) {
	model := &models.MRISpecifics{}

	// Mapping regular DICOM fields
	// Set ReceiveCoilName
	elem, err := dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x1250})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.ReceiveCoilName = v
			case []string:
				model.ReceiveCoilName = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set NumberOfFrames
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0028, Element: 0x0008})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedInt, err := strconv.Atoi(v)
				if err == nil {
					model.NumberOfFrames = parsedInt
				}
			case []string:
				parsedInt, err := strconv.Atoi(v[0])
				if err == nil {
					model.NumberOfFrames = parsedInt
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set SamplesPerPixel
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0028, Element: 0x0002})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedInt, err := strconv.Atoi(v)
				if err == nil {
					model.SamplesPerPixel = parsedInt
				}
			case []string:
				parsedInt, err := strconv.Atoi(v[0])
				if err == nil {
					model.SamplesPerPixel = parsedInt
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set PhotometricInterpretation
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0028, Element: 0x0004})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.PhotometricInterpretation = v
			case []string:
				model.PhotometricInterpretation = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set BitsStored
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0028, Element: 0x0101})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedInt, err := strconv.Atoi(v)
				if err == nil {
					model.BitsStored = parsedInt
				}
			case []string:
				parsedInt, err := strconv.Atoi(v[0])
				if err == nil {
					model.BitsStored = parsedInt
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set ImageType
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x0008})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.ImageType = v
			case []string:
				model.ImageType = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set AcquisitionMatrix
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x1310})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.AcquisitionMatrix = v
			case []string:
				model.AcquisitionMatrix = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set AcquisitionDuration
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x9073})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.AcquisitionDuration = v
			case []string:
				model.AcquisitionDuration = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set AngioFlag
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0025})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.AngioFlag = v
			case []string:
				model.AngioFlag = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set BeatRejectionFlag
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x1080})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.BeatRejectionFlag = v
			case []string:
				model.BeatRejectionFlag = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set BitsAllocated
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0028, Element: 0x0100})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedInt, err := strconv.Atoi(v)
				if err == nil {
					model.BitsAllocated = parsedInt
				}
			case []string:
				parsedInt, err := strconv.Atoi(v[0])
				if err == nil {
					model.BitsAllocated = parsedInt
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set DBDt
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x1318})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.DBDt = v
			case []string:
				model.DBDt = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set EchoNumber
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0086})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedInt, err := strconv.Atoi(v)
				if err == nil {
					model.EchoNumber = parsedInt
				}
			case []string:
				parsedInt, err := strconv.Atoi(v[0])
				if err == nil {
					model.EchoNumber = parsedInt
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set EchoPlanerPulseSequence
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x9018})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.EchoPlanerPulseSequence = v
			case []string:
				model.EchoPlanerPulseSequence = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set EchoTime
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0081})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedFloat, err := strconv.ParseFloat(v, 64)
				if err == nil {
					model.EchoTime = parsedFloat
				}
			case []string:
				parsedFloat, err := strconv.ParseFloat(v[0], 64)
				if err == nil {
					model.EchoTime = parsedFloat
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set EchoTrainLength
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0091})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedInt, err := strconv.Atoi(v)
				if err == nil {
					model.EchoTrainLength = parsedInt
				}
			case []string:
				parsedInt, err := strconv.Atoi(v[0])
				if err == nil {
					model.EchoTrainLength = parsedInt
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set FlipAngle
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x1314})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.FlipAngle = v
			case []string:
				model.FlipAngle = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set HighBit
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0028, Element: 0x0102})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.HighBit = v
			case []string:
				model.HighBit = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set HighRRValue
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x1082})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.HighRRValue = v
			case []string:
				model.HighRRValue = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set ImagedNucleus
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0085})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.ImagedNucleus = v
			case []string:
				model.ImagedNucleus = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set ImagesInAcquisition
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0020, Element: 0x1002})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedInt, err := strconv.Atoi(v)
				if err == nil {
					model.ImagesInAcquisition = parsedInt
				}
			case []string:
				parsedInt, err := strconv.Atoi(v[0])
				if err == nil {
					model.ImagesInAcquisition = parsedInt
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set ImagingFrequency
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0084})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.ImagingFrequency = v
			case []string:
				model.ImagingFrequency = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set InPlanePhaseEncodingDirection
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x1312})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.InPlanePhaseEncodingDirection = v
			case []string:
				model.InPlanePhaseEncodingDirection = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set IntervalsAcquired
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x1083})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.IntervalsAcquired = v
			case []string:
				model.IntervalsAcquired = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set IntervalsRejected
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x1084})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.IntervalsRejected = v
			case []string:
				model.IntervalsRejected = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set InversionTime
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x9079})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedFloat, err := strconv.ParseFloat(v, 64)
				if err == nil {
					model.InversionTime = parsedFloat
				}
			case []string:
				parsedFloat, err := strconv.ParseFloat(v[0], 64)
				if err == nil {
					model.InversionTime = parsedFloat
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set LowRRValue
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x1081})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.LowRRValue = v
			case []string:
				model.LowRRValue = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set MagneticFieldStrength
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0087})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.MagneticFieldStrength = v
			case []string:
				model.MagneticFieldStrength = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set MultiPlanarExcitation
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x9012})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.MultiPlanarExcitation = v
			case []string:
				model.MultiPlanarExcitation = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set MultipleSpinEcho
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x9011})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.MultipleSpinEcho = v
			case []string:
				model.MultipleSpinEcho = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set NominalInterval
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x1062})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.NominalInterval = v
			case []string:
				model.NominalInterval = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set NumberOfAverages
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0083})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedFloat, err := strconv.ParseFloat(v, 64)
				if err == nil {
					model.NumberOfAverages = parsedFloat
				}
			case []string:
				parsedFloat, err := strconv.ParseFloat(v[0], 64)
				if err == nil {
					model.NumberOfAverages = parsedFloat
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set NumberOfPhaseEncodingSteps
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0089})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedInt, err := strconv.Atoi(v)
				if err == nil {
					model.NumberOfPhaseEncodingSteps = parsedInt
				}
			case []string:
				parsedInt, err := strconv.Atoi(v[0])
				if err == nil {
					model.NumberOfPhaseEncodingSteps = parsedInt
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set NumberOfTemporalPositions
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0020, Element: 0x0105})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedInt, err := strconv.Atoi(v)
				if err == nil {
					model.NumberOfTemporalPositions = parsedInt
				}
			case []string:
				parsedInt, err := strconv.Atoi(v[0])
				if err == nil {
					model.NumberOfTemporalPositions = parsedInt
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set PercentPhaseFieldOfView
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0094})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.PercentPhaseFieldOfView = v
			case []string:
				model.PercentPhaseFieldOfView = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set PercentSampling
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0093})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.PercentSampling = v
			case []string:
				model.PercentSampling = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set PixelAspectRatio
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0028, Element: 0x0034})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.PixelAspectRatio = v
			case []string:
				model.PixelAspectRatio = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set PixelBandwidth
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0095})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.PixelBandwidth = v
			case []string:
				model.PixelBandwidth = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set PixelSpacing
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0028, Element: 0x0030})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.PixelSpacing = v
			case []string:
				model.PixelSpacing = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set PlanarConfiguration
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0028, Element: 0x0006})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.PlanarConfiguration = v
			case []string:
				model.PlanarConfiguration = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set PulseSequenceName
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x9005})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.PulseSequenceName = v
			case []string:
				model.PulseSequenceName = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set ReconstructionDiameter
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x1100})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.ReconstructionDiameter = v
			case []string:
				model.ReconstructionDiameter = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set RepetitionTime
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0080})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedFloat, err := strconv.ParseFloat(v, 64)
				if err == nil {
					model.RepetitionTime = parsedFloat
				}
			case []string:
				parsedFloat, err := strconv.ParseFloat(v[0], 64)
				if err == nil {
					model.RepetitionTime = parsedFloat
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set SaturationRecovery
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x9024})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.SaturationRecovery = v
			case []string:
				model.SaturationRecovery = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set ScanningSequence
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0020})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.ScanningSequence = v
			case []string:
				model.ScanningSequence = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set ScanOptions
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0022})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.ScanOptions = v
			case []string:
				model.ScanOptions = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set SequenceName
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0024})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.SequenceName = v
			case []string:
				model.SequenceName = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set SequenceVariant
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0021})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.SequenceVariant = v
			case []string:
				model.SequenceVariant = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set SliceThickness
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0050})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedFloat, err := strconv.ParseFloat(v, 64)
				if err == nil {
					model.SliceThickness = parsedFloat
				}
			case []string:
				parsedFloat, err := strconv.ParseFloat(v[0], 64)
				if err == nil {
					model.SliceThickness = parsedFloat
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set SpacingBetweenSlices
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x0088})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedFloat, err := strconv.ParseFloat(v, 64)
				if err == nil {
					model.SpacingBetweenSlices = parsedFloat
				}
			case []string:
				parsedFloat, err := strconv.ParseFloat(v[0], 64)
				if err == nil {
					model.SpacingBetweenSlices = parsedFloat
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set SteadyStatePulseSequence
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x9017})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.SteadyStatePulseSequence = v
			case []string:
				model.SteadyStatePulseSequence = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set TemporalPositionIdentifier
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0020, Element: 0x0100})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.TemporalPositionIdentifier = v
			case []string:
				model.TemporalPositionIdentifier = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set TemporalResolution
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0020, Element: 0x0110})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedFloat, err := strconv.ParseFloat(v, 64)
				if err == nil {
					model.TemporalResolution = parsedFloat
				}
			case []string:
				parsedFloat, err := strconv.ParseFloat(v[0], 64)
				if err == nil {
					model.TemporalResolution = parsedFloat
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set TransmitCoilName
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x1251})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.TransmitCoilName = v
			case []string:
				model.TransmitCoilName = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set VariableFlipAngleFlag
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0018, Element: 0x1315})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.VariableFlipAngleFlag = v
			case []string:
				model.VariableFlipAngleFlag = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set PulseSequence
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0027, Element: 0x1032})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedInt, err := strconv.Atoi(v)
				if err == nil {
					model.PulseSequence = parsedInt
				}
			case []string:
				parsedInt, err := strconv.Atoi(v[0])
				if err == nil {
					model.PulseSequence = parsedInt
				}
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set AcquisitionContrast
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x0008, Element: 0x9209})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				model.AcquisitionContrast = v
			case []string:
				model.AcquisitionContrast = v[0]
			default:
				// Handle other types if necessary
			}
		}
	}
	// Set WaterFatShift
	elem, err = dataset.FindElementByTag(tag.Tag{Group: 0x2001, Element: 0x1022})
	if err == nil {
		val := elem.Value.GetValue()
		if val != nil {
			// Assuming val is always a string or []string
			switch v := val.(type) {
			case string:
				parsedFloat, err := strconv.ParseFloat(v, 64)
				if err == nil {
					model.WaterFatShift = parsedFloat
				}
			case []string:
				parsedFloat, err := strconv.ParseFloat(v[0], 64)
				if err == nil {
					model.WaterFatShift = parsedFloat
				}
			default:
				// Handle other types if necessary
			}
		}
	}

	// Handling datetime fields

	return model, nil
}
