_target_: ahcore.transforms.pre_transforms.PreTransformFactory
transforms:
  - _target_: ahcore.transforms.pre_transforms.ToDict
    keys: ['image', 'coordinates', 'mpp', 'path', 'region_index', 'annotations']
  - _target_: ahcore.transforms.pre_transforms.ImageToTensor
  - _target_: ahcore.transforms.pre_transforms.PolygonsToMask
    num_classes: ${data_description.num_classes}
  - _target_: ahcore.transforms.pre_transforms.AllowCollate
