/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as TermsImport } from "./routes/terms";
import { Route as RegisterImport } from "./routes/register";
import { Route as PrivacyImport } from "./routes/privacy";
import { Route as LoginImport } from "./routes/login";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated/route";
import { Route as IndexImport } from "./routes/index";
import { Route as AccountResetpasswordImport } from "./routes/account/reset_password";
import { Route as AccountResendActivationImport } from "./routes/account/resend-activation";
import { Route as AccountActivateImport } from "./routes/account/activate";
import { Route as AuthenticatedAccountImport } from "./routes/_authenticated/account";
import { Route as AuthenticatedVIndexImport } from "./routes/_authenticated/v/index";
import { Route as AuthenticatedStudiesIndexImport } from "./routes/_authenticated/studies/index";
import { Route as AuthenticatedAdminIndexImport } from "./routes/_authenticated/admin/index";
import { Route as AuthenticatedISlideUidImport } from "./routes/_authenticated/i/$slideUid";
import { Route as AuthenticatedVCaseUidIndexImport } from "./routes/_authenticated/v/$caseUid/index";
import { Route as AuthenticatedStudiesStudyUidIndexImport } from "./routes/_authenticated/studies/$studyUid/index";
import { Route as AuthenticatedAdminUsersIndexImport } from "./routes/_authenticated/admin/users/index";
import { Route as AuthenticatedAdminTenantsIndexImport } from "./routes/_authenticated/admin/tenants/index";
import { Route as AuthenticatedAdminStudiesIndexImport } from "./routes/_authenticated/admin/studies/index";
import { Route as AuthenticatedAdminSlidesIndexImport } from "./routes/_authenticated/admin/slides/index";
import { Route as AuthenticatedAdminRolesIndexImport } from "./routes/_authenticated/admin/roles/index";
import { Route as AuthenticatedAdminPermissionsIndexImport } from "./routes/_authenticated/admin/permissions/index";
import { Route as AuthenticatedAdminGroupsIndexImport } from "./routes/_authenticated/admin/groups/index";
import { Route as AuthenticatedAdminCasesIndexImport } from "./routes/_authenticated/admin/cases/index";
import { Route as AuthenticatedAdminAlgorithmsIndexImport } from "./routes/_authenticated/admin/algorithms/index";
import { Route as AuthenticatedStudiesStudyUidSettingsImport } from "./routes/_authenticated/studies/$studyUid/settings";
import { Route as AuthenticatedAdminUsersUserUidImport } from "./routes/_authenticated/admin/users/$userUid";
import { Route as AuthenticatedAdminTenantsTenantUidImport } from "./routes/_authenticated/admin/tenants/$tenantUid";
import { Route as AuthenticatedAdminSystemSettingsImport } from "./routes/_authenticated/admin/system/settings";
import { Route as AuthenticatedAdminSystemQueueImport } from "./routes/_authenticated/admin/system/queue";
import { Route as AuthenticatedAdminSystemNotificationsImport } from "./routes/_authenticated/admin/system/notifications";
import { Route as AuthenticatedAdminSystemMonitorImport } from "./routes/_authenticated/admin/system/monitor";
import { Route as AuthenticatedAdminSystemEmailImport } from "./routes/_authenticated/admin/system/email";
import { Route as AuthenticatedAdminSlidesSlideUidImport } from "./routes/_authenticated/admin/slides/$slideUid";
import { Route as AuthenticatedAdminCasesCaseUidImport } from "./routes/_authenticated/admin/cases/$caseUid";
import { Route as AuthenticatedAdminAlgorithmsAlgorithmIdImport } from "./routes/_authenticated/admin/algorithms/$algorithmId";
import { Route as AuthenticatedAdminStudiesStudyUidIndexImport } from "./routes/_authenticated/admin/studies/$studyUid/index";
import { Route as AuthenticatedVCaseUidISlideUidImport } from "./routes/_authenticated/v/$caseUid/i/$slideUid";
import { Route as AuthenticatedStudiesStudyUidSettingsTabImport } from "./routes/_authenticated/studies/$studyUid/settings.$tab";
import { Route as AuthenticatedAdminStudiesStudyUidPermissionsImport } from "./routes/_authenticated/admin/studies/$studyUid/permissions";
import { Route as AuthenticatedStudiesStudyUidVCaseUidIndexImport } from "./routes/_authenticated/studies/$studyUid/v/$caseUid/index";
import { Route as AuthenticatedStudiesStudyUidVCaseUidISlideUidImport } from "./routes/_authenticated/studies/$studyUid/v/$caseUid/i/$slideUid";

// Create/Update Routes

const TermsRoute = TermsImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => rootRoute,
} as any);

const RegisterRoute = RegisterImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRoute,
} as any);

const PrivacyRoute = PrivacyImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as any);

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const AccountResetpasswordRoute = AccountResetpasswordImport.update({
  id: "/account/reset_password",
  path: "/account/reset_password",
  getParentRoute: () => rootRoute,
} as any);

const AccountResendActivationRoute = AccountResendActivationImport.update({
  id: "/account/resend-activation",
  path: "/account/resend-activation",
  getParentRoute: () => rootRoute,
} as any);

const AccountActivateRoute = AccountActivateImport.update({
  id: "/account/activate",
  path: "/account/activate",
  getParentRoute: () => rootRoute,
} as any);

const AuthenticatedAccountRoute = AuthenticatedAccountImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);

const AuthenticatedVIndexRoute = AuthenticatedVIndexImport.update({
  id: "/v/",
  path: "/v/",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);

const AuthenticatedStudiesIndexRoute = AuthenticatedStudiesIndexImport.update({
  id: "/studies/",
  path: "/studies/",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);

const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexImport.update({
  id: "/admin/",
  path: "/admin/",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);

const AuthenticatedISlideUidRoute = AuthenticatedISlideUidImport.update({
  id: "/i/$slideUid",
  path: "/i/$slideUid",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);

const AuthenticatedVCaseUidIndexRoute = AuthenticatedVCaseUidIndexImport.update(
  {
    id: "/v/$caseUid/",
    path: "/v/$caseUid/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any
);

const AuthenticatedStudiesStudyUidIndexRoute =
  AuthenticatedStudiesStudyUidIndexImport.update({
    id: "/studies/$studyUid/",
    path: "/studies/$studyUid/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexImport.update({
    id: "/admin/users/",
    path: "/admin/users/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminTenantsIndexRoute =
  AuthenticatedAdminTenantsIndexImport.update({
    id: "/admin/tenants/",
    path: "/admin/tenants/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminStudiesIndexRoute =
  AuthenticatedAdminStudiesIndexImport.update({
    id: "/admin/studies/",
    path: "/admin/studies/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminSlidesIndexRoute =
  AuthenticatedAdminSlidesIndexImport.update({
    id: "/admin/slides/",
    path: "/admin/slides/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminRolesIndexRoute =
  AuthenticatedAdminRolesIndexImport.update({
    id: "/admin/roles/",
    path: "/admin/roles/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminPermissionsIndexRoute =
  AuthenticatedAdminPermissionsIndexImport.update({
    id: "/admin/permissions/",
    path: "/admin/permissions/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminGroupsIndexRoute =
  AuthenticatedAdminGroupsIndexImport.update({
    id: "/admin/groups/",
    path: "/admin/groups/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminCasesIndexRoute =
  AuthenticatedAdminCasesIndexImport.update({
    id: "/admin/cases/",
    path: "/admin/cases/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminAlgorithmsIndexRoute =
  AuthenticatedAdminAlgorithmsIndexImport.update({
    id: "/admin/algorithms/",
    path: "/admin/algorithms/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedStudiesStudyUidSettingsRoute =
  AuthenticatedStudiesStudyUidSettingsImport.update({
    id: "/studies/$studyUid/settings",
    path: "/studies/$studyUid/settings",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminUsersUserUidRoute =
  AuthenticatedAdminUsersUserUidImport.update({
    id: "/admin/users/$userUid",
    path: "/admin/users/$userUid",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminTenantsTenantUidRoute =
  AuthenticatedAdminTenantsTenantUidImport.update({
    id: "/admin/tenants/$tenantUid",
    path: "/admin/tenants/$tenantUid",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminSystemSettingsRoute =
  AuthenticatedAdminSystemSettingsImport.update({
    id: "/admin/system/settings",
    path: "/admin/system/settings",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminSystemQueueRoute =
  AuthenticatedAdminSystemQueueImport.update({
    id: "/admin/system/queue",
    path: "/admin/system/queue",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminSystemNotificationsRoute =
  AuthenticatedAdminSystemNotificationsImport.update({
    id: "/admin/system/notifications",
    path: "/admin/system/notifications",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminSystemMonitorRoute =
  AuthenticatedAdminSystemMonitorImport.update({
    id: "/admin/system/monitor",
    path: "/admin/system/monitor",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminSystemEmailRoute =
  AuthenticatedAdminSystemEmailImport.update({
    id: "/admin/system/email",
    path: "/admin/system/email",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminSlidesSlideUidRoute =
  AuthenticatedAdminSlidesSlideUidImport.update({
    id: "/admin/slides/$slideUid",
    path: "/admin/slides/$slideUid",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminCasesCaseUidRoute =
  AuthenticatedAdminCasesCaseUidImport.update({
    id: "/admin/cases/$caseUid",
    path: "/admin/cases/$caseUid",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminAlgorithmsAlgorithmIdRoute =
  AuthenticatedAdminAlgorithmsAlgorithmIdImport.update({
    id: "/admin/algorithms/$algorithmId",
    path: "/admin/algorithms/$algorithmId",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedAdminStudiesStudyUidIndexRoute =
  AuthenticatedAdminStudiesStudyUidIndexImport.update({
    id: "/admin/studies/$studyUid/",
    path: "/admin/studies/$studyUid/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedVCaseUidISlideUidRoute =
  AuthenticatedVCaseUidISlideUidImport.update({
    id: "/v/$caseUid/i/$slideUid",
    path: "/v/$caseUid/i/$slideUid",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedStudiesStudyUidSettingsTabRoute =
  AuthenticatedStudiesStudyUidSettingsTabImport.update({
    id: "/$tab",
    path: "/$tab",
    getParentRoute: () => AuthenticatedStudiesStudyUidSettingsRoute,
  } as any);

const AuthenticatedAdminStudiesStudyUidPermissionsRoute =
  AuthenticatedAdminStudiesStudyUidPermissionsImport.update({
    id: "/admin/studies/$studyUid/permissions",
    path: "/admin/studies/$studyUid/permissions",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedStudiesStudyUidVCaseUidIndexRoute =
  AuthenticatedStudiesStudyUidVCaseUidIndexImport.update({
    id: "/studies/$studyUid/v/$caseUid/",
    path: "/studies/$studyUid/v/$caseUid/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

const AuthenticatedStudiesStudyUidVCaseUidISlideUidRoute =
  AuthenticatedStudiesStudyUidVCaseUidISlideUidImport.update({
    id: "/studies/$studyUid/v/$caseUid/i/$slideUid",
    path: "/studies/$studyUid/v/$caseUid/i/$slideUid",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    "/privacy": {
      id: "/privacy";
      path: "/privacy";
      fullPath: "/privacy";
      preLoaderRoute: typeof PrivacyImport;
      parentRoute: typeof rootRoute;
    };
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterImport;
      parentRoute: typeof rootRoute;
    };
    "/terms": {
      id: "/terms";
      path: "/terms";
      fullPath: "/terms";
      preLoaderRoute: typeof TermsImport;
      parentRoute: typeof rootRoute;
    };
    "/_authenticated/account": {
      id: "/_authenticated/account";
      path: "/account";
      fullPath: "/account";
      preLoaderRoute: typeof AuthenticatedAccountImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/account/activate": {
      id: "/account/activate";
      path: "/account/activate";
      fullPath: "/account/activate";
      preLoaderRoute: typeof AccountActivateImport;
      parentRoute: typeof rootRoute;
    };
    "/account/resend-activation": {
      id: "/account/resend-activation";
      path: "/account/resend-activation";
      fullPath: "/account/resend-activation";
      preLoaderRoute: typeof AccountResendActivationImport;
      parentRoute: typeof rootRoute;
    };
    "/account/reset_password": {
      id: "/account/reset_password";
      path: "/account/reset_password";
      fullPath: "/account/reset_password";
      preLoaderRoute: typeof AccountResetpasswordImport;
      parentRoute: typeof rootRoute;
    };
    "/_authenticated/i/$slideUid": {
      id: "/_authenticated/i/$slideUid";
      path: "/i/$slideUid";
      fullPath: "/i/$slideUid";
      preLoaderRoute: typeof AuthenticatedISlideUidImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/": {
      id: "/_authenticated/admin/";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AuthenticatedAdminIndexImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/studies/": {
      id: "/_authenticated/studies/";
      path: "/studies";
      fullPath: "/studies";
      preLoaderRoute: typeof AuthenticatedStudiesIndexImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/v/": {
      id: "/_authenticated/v/";
      path: "/v";
      fullPath: "/v";
      preLoaderRoute: typeof AuthenticatedVIndexImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/algorithms/$algorithmId": {
      id: "/_authenticated/admin/algorithms/$algorithmId";
      path: "/admin/algorithms/$algorithmId";
      fullPath: "/admin/algorithms/$algorithmId";
      preLoaderRoute: typeof AuthenticatedAdminAlgorithmsAlgorithmIdImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/cases/$caseUid": {
      id: "/_authenticated/admin/cases/$caseUid";
      path: "/admin/cases/$caseUid";
      fullPath: "/admin/cases/$caseUid";
      preLoaderRoute: typeof AuthenticatedAdminCasesCaseUidImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/slides/$slideUid": {
      id: "/_authenticated/admin/slides/$slideUid";
      path: "/admin/slides/$slideUid";
      fullPath: "/admin/slides/$slideUid";
      preLoaderRoute: typeof AuthenticatedAdminSlidesSlideUidImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/system/email": {
      id: "/_authenticated/admin/system/email";
      path: "/admin/system/email";
      fullPath: "/admin/system/email";
      preLoaderRoute: typeof AuthenticatedAdminSystemEmailImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/system/monitor": {
      id: "/_authenticated/admin/system/monitor";
      path: "/admin/system/monitor";
      fullPath: "/admin/system/monitor";
      preLoaderRoute: typeof AuthenticatedAdminSystemMonitorImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/system/notifications": {
      id: "/_authenticated/admin/system/notifications";
      path: "/admin/system/notifications";
      fullPath: "/admin/system/notifications";
      preLoaderRoute: typeof AuthenticatedAdminSystemNotificationsImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/system/queue": {
      id: "/_authenticated/admin/system/queue";
      path: "/admin/system/queue";
      fullPath: "/admin/system/queue";
      preLoaderRoute: typeof AuthenticatedAdminSystemQueueImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/system/settings": {
      id: "/_authenticated/admin/system/settings";
      path: "/admin/system/settings";
      fullPath: "/admin/system/settings";
      preLoaderRoute: typeof AuthenticatedAdminSystemSettingsImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/tenants/$tenantUid": {
      id: "/_authenticated/admin/tenants/$tenantUid";
      path: "/admin/tenants/$tenantUid";
      fullPath: "/admin/tenants/$tenantUid";
      preLoaderRoute: typeof AuthenticatedAdminTenantsTenantUidImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/users/$userUid": {
      id: "/_authenticated/admin/users/$userUid";
      path: "/admin/users/$userUid";
      fullPath: "/admin/users/$userUid";
      preLoaderRoute: typeof AuthenticatedAdminUsersUserUidImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/studies/$studyUid/settings": {
      id: "/_authenticated/studies/$studyUid/settings";
      path: "/studies/$studyUid/settings";
      fullPath: "/studies/$studyUid/settings";
      preLoaderRoute: typeof AuthenticatedStudiesStudyUidSettingsImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/algorithms/": {
      id: "/_authenticated/admin/algorithms/";
      path: "/admin/algorithms";
      fullPath: "/admin/algorithms";
      preLoaderRoute: typeof AuthenticatedAdminAlgorithmsIndexImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/cases/": {
      id: "/_authenticated/admin/cases/";
      path: "/admin/cases";
      fullPath: "/admin/cases";
      preLoaderRoute: typeof AuthenticatedAdminCasesIndexImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/groups/": {
      id: "/_authenticated/admin/groups/";
      path: "/admin/groups";
      fullPath: "/admin/groups";
      preLoaderRoute: typeof AuthenticatedAdminGroupsIndexImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/permissions/": {
      id: "/_authenticated/admin/permissions/";
      path: "/admin/permissions";
      fullPath: "/admin/permissions";
      preLoaderRoute: typeof AuthenticatedAdminPermissionsIndexImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/roles/": {
      id: "/_authenticated/admin/roles/";
      path: "/admin/roles";
      fullPath: "/admin/roles";
      preLoaderRoute: typeof AuthenticatedAdminRolesIndexImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/slides/": {
      id: "/_authenticated/admin/slides/";
      path: "/admin/slides";
      fullPath: "/admin/slides";
      preLoaderRoute: typeof AuthenticatedAdminSlidesIndexImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/studies/": {
      id: "/_authenticated/admin/studies/";
      path: "/admin/studies";
      fullPath: "/admin/studies";
      preLoaderRoute: typeof AuthenticatedAdminStudiesIndexImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/tenants/": {
      id: "/_authenticated/admin/tenants/";
      path: "/admin/tenants";
      fullPath: "/admin/tenants";
      preLoaderRoute: typeof AuthenticatedAdminTenantsIndexImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/users/": {
      id: "/_authenticated/admin/users/";
      path: "/admin/users";
      fullPath: "/admin/users";
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/studies/$studyUid/": {
      id: "/_authenticated/studies/$studyUid/";
      path: "/studies/$studyUid";
      fullPath: "/studies/$studyUid";
      preLoaderRoute: typeof AuthenticatedStudiesStudyUidIndexImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/v/$caseUid/": {
      id: "/_authenticated/v/$caseUid/";
      path: "/v/$caseUid";
      fullPath: "/v/$caseUid";
      preLoaderRoute: typeof AuthenticatedVCaseUidIndexImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/studies/$studyUid/permissions": {
      id: "/_authenticated/admin/studies/$studyUid/permissions";
      path: "/admin/studies/$studyUid/permissions";
      fullPath: "/admin/studies/$studyUid/permissions";
      preLoaderRoute: typeof AuthenticatedAdminStudiesStudyUidPermissionsImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/studies/$studyUid/settings/$tab": {
      id: "/_authenticated/studies/$studyUid/settings/$tab";
      path: "/$tab";
      fullPath: "/studies/$studyUid/settings/$tab";
      preLoaderRoute: typeof AuthenticatedStudiesStudyUidSettingsTabImport;
      parentRoute: typeof AuthenticatedStudiesStudyUidSettingsImport;
    };
    "/_authenticated/v/$caseUid/i/$slideUid": {
      id: "/_authenticated/v/$caseUid/i/$slideUid";
      path: "/v/$caseUid/i/$slideUid";
      fullPath: "/v/$caseUid/i/$slideUid";
      preLoaderRoute: typeof AuthenticatedVCaseUidISlideUidImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/admin/studies/$studyUid/": {
      id: "/_authenticated/admin/studies/$studyUid/";
      path: "/admin/studies/$studyUid";
      fullPath: "/admin/studies/$studyUid";
      preLoaderRoute: typeof AuthenticatedAdminStudiesStudyUidIndexImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/studies/$studyUid/v/$caseUid/": {
      id: "/_authenticated/studies/$studyUid/v/$caseUid/";
      path: "/studies/$studyUid/v/$caseUid";
      fullPath: "/studies/$studyUid/v/$caseUid";
      preLoaderRoute: typeof AuthenticatedStudiesStudyUidVCaseUidIndexImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
    "/_authenticated/studies/$studyUid/v/$caseUid/i/$slideUid": {
      id: "/_authenticated/studies/$studyUid/v/$caseUid/i/$slideUid";
      path: "/studies/$studyUid/v/$caseUid/i/$slideUid";
      fullPath: "/studies/$studyUid/v/$caseUid/i/$slideUid";
      preLoaderRoute: typeof AuthenticatedStudiesStudyUidVCaseUidISlideUidImport;
      parentRoute: typeof AuthenticatedRouteImport;
    };
  }
}

// Create and export the route tree

interface AuthenticatedStudiesStudyUidSettingsRouteChildren {
  AuthenticatedStudiesStudyUidSettingsTabRoute: typeof AuthenticatedStudiesStudyUidSettingsTabRoute;
}

const AuthenticatedStudiesStudyUidSettingsRouteChildren: AuthenticatedStudiesStudyUidSettingsRouteChildren =
  {
    AuthenticatedStudiesStudyUidSettingsTabRoute:
      AuthenticatedStudiesStudyUidSettingsTabRoute,
  };

const AuthenticatedStudiesStudyUidSettingsRouteWithChildren =
  AuthenticatedStudiesStudyUidSettingsRoute._addFileChildren(
    AuthenticatedStudiesStudyUidSettingsRouteChildren
  );

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute;
  AuthenticatedISlideUidRoute: typeof AuthenticatedISlideUidRoute;
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute;
  AuthenticatedStudiesIndexRoute: typeof AuthenticatedStudiesIndexRoute;
  AuthenticatedVIndexRoute: typeof AuthenticatedVIndexRoute;
  AuthenticatedAdminAlgorithmsAlgorithmIdRoute: typeof AuthenticatedAdminAlgorithmsAlgorithmIdRoute;
  AuthenticatedAdminCasesCaseUidRoute: typeof AuthenticatedAdminCasesCaseUidRoute;
  AuthenticatedAdminSlidesSlideUidRoute: typeof AuthenticatedAdminSlidesSlideUidRoute;
  AuthenticatedAdminSystemEmailRoute: typeof AuthenticatedAdminSystemEmailRoute;
  AuthenticatedAdminSystemMonitorRoute: typeof AuthenticatedAdminSystemMonitorRoute;
  AuthenticatedAdminSystemNotificationsRoute: typeof AuthenticatedAdminSystemNotificationsRoute;
  AuthenticatedAdminSystemQueueRoute: typeof AuthenticatedAdminSystemQueueRoute;
  AuthenticatedAdminSystemSettingsRoute: typeof AuthenticatedAdminSystemSettingsRoute;
  AuthenticatedAdminTenantsTenantUidRoute: typeof AuthenticatedAdminTenantsTenantUidRoute;
  AuthenticatedAdminUsersUserUidRoute: typeof AuthenticatedAdminUsersUserUidRoute;
  AuthenticatedStudiesStudyUidSettingsRoute: typeof AuthenticatedStudiesStudyUidSettingsRouteWithChildren;
  AuthenticatedAdminAlgorithmsIndexRoute: typeof AuthenticatedAdminAlgorithmsIndexRoute;
  AuthenticatedAdminCasesIndexRoute: typeof AuthenticatedAdminCasesIndexRoute;
  AuthenticatedAdminGroupsIndexRoute: typeof AuthenticatedAdminGroupsIndexRoute;
  AuthenticatedAdminPermissionsIndexRoute: typeof AuthenticatedAdminPermissionsIndexRoute;
  AuthenticatedAdminRolesIndexRoute: typeof AuthenticatedAdminRolesIndexRoute;
  AuthenticatedAdminSlidesIndexRoute: typeof AuthenticatedAdminSlidesIndexRoute;
  AuthenticatedAdminStudiesIndexRoute: typeof AuthenticatedAdminStudiesIndexRoute;
  AuthenticatedAdminTenantsIndexRoute: typeof AuthenticatedAdminTenantsIndexRoute;
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute;
  AuthenticatedStudiesStudyUidIndexRoute: typeof AuthenticatedStudiesStudyUidIndexRoute;
  AuthenticatedVCaseUidIndexRoute: typeof AuthenticatedVCaseUidIndexRoute;
  AuthenticatedAdminStudiesStudyUidPermissionsRoute: typeof AuthenticatedAdminStudiesStudyUidPermissionsRoute;
  AuthenticatedVCaseUidISlideUidRoute: typeof AuthenticatedVCaseUidISlideUidRoute;
  AuthenticatedAdminStudiesStudyUidIndexRoute: typeof AuthenticatedAdminStudiesStudyUidIndexRoute;
  AuthenticatedStudiesStudyUidVCaseUidIndexRoute: typeof AuthenticatedStudiesStudyUidVCaseUidIndexRoute;
  AuthenticatedStudiesStudyUidVCaseUidISlideUidRoute: typeof AuthenticatedStudiesStudyUidVCaseUidISlideUidRoute;
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedISlideUidRoute: AuthenticatedISlideUidRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedStudiesIndexRoute: AuthenticatedStudiesIndexRoute,
  AuthenticatedVIndexRoute: AuthenticatedVIndexRoute,
  AuthenticatedAdminAlgorithmsAlgorithmIdRoute:
    AuthenticatedAdminAlgorithmsAlgorithmIdRoute,
  AuthenticatedAdminCasesCaseUidRoute: AuthenticatedAdminCasesCaseUidRoute,
  AuthenticatedAdminSlidesSlideUidRoute: AuthenticatedAdminSlidesSlideUidRoute,
  AuthenticatedAdminSystemEmailRoute: AuthenticatedAdminSystemEmailRoute,
  AuthenticatedAdminSystemMonitorRoute: AuthenticatedAdminSystemMonitorRoute,
  AuthenticatedAdminSystemNotificationsRoute:
    AuthenticatedAdminSystemNotificationsRoute,
  AuthenticatedAdminSystemQueueRoute: AuthenticatedAdminSystemQueueRoute,
  AuthenticatedAdminSystemSettingsRoute: AuthenticatedAdminSystemSettingsRoute,
  AuthenticatedAdminTenantsTenantUidRoute:
    AuthenticatedAdminTenantsTenantUidRoute,
  AuthenticatedAdminUsersUserUidRoute: AuthenticatedAdminUsersUserUidRoute,
  AuthenticatedStudiesStudyUidSettingsRoute:
    AuthenticatedStudiesStudyUidSettingsRouteWithChildren,
  AuthenticatedAdminAlgorithmsIndexRoute:
    AuthenticatedAdminAlgorithmsIndexRoute,
  AuthenticatedAdminCasesIndexRoute: AuthenticatedAdminCasesIndexRoute,
  AuthenticatedAdminGroupsIndexRoute: AuthenticatedAdminGroupsIndexRoute,
  AuthenticatedAdminPermissionsIndexRoute:
    AuthenticatedAdminPermissionsIndexRoute,
  AuthenticatedAdminRolesIndexRoute: AuthenticatedAdminRolesIndexRoute,
  AuthenticatedAdminSlidesIndexRoute: AuthenticatedAdminSlidesIndexRoute,
  AuthenticatedAdminStudiesIndexRoute: AuthenticatedAdminStudiesIndexRoute,
  AuthenticatedAdminTenantsIndexRoute: AuthenticatedAdminTenantsIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  AuthenticatedStudiesStudyUidIndexRoute:
    AuthenticatedStudiesStudyUidIndexRoute,
  AuthenticatedVCaseUidIndexRoute: AuthenticatedVCaseUidIndexRoute,
  AuthenticatedAdminStudiesStudyUidPermissionsRoute:
    AuthenticatedAdminStudiesStudyUidPermissionsRoute,
  AuthenticatedVCaseUidISlideUidRoute: AuthenticatedVCaseUidISlideUidRoute,
  AuthenticatedAdminStudiesStudyUidIndexRoute:
    AuthenticatedAdminStudiesStudyUidIndexRoute,
  AuthenticatedStudiesStudyUidVCaseUidIndexRoute:
    AuthenticatedStudiesStudyUidVCaseUidIndexRoute,
  AuthenticatedStudiesStudyUidVCaseUidISlideUidRoute:
    AuthenticatedStudiesStudyUidVCaseUidISlideUidRoute,
};

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "": typeof AuthenticatedRouteRouteWithChildren;
  "/login": typeof LoginRoute;
  "/privacy": typeof PrivacyRoute;
  "/register": typeof RegisterRoute;
  "/terms": typeof TermsRoute;
  "/account": typeof AuthenticatedAccountRoute;
  "/account/activate": typeof AccountActivateRoute;
  "/account/resend-activation": typeof AccountResendActivationRoute;
  "/account/reset_password": typeof AccountResetpasswordRoute;
  "/i/$slideUid": typeof AuthenticatedISlideUidRoute;
  "/admin": typeof AuthenticatedAdminIndexRoute;
  "/studies": typeof AuthenticatedStudiesIndexRoute;
  "/v": typeof AuthenticatedVIndexRoute;
  "/admin/algorithms/$algorithmId": typeof AuthenticatedAdminAlgorithmsAlgorithmIdRoute;
  "/admin/cases/$caseUid": typeof AuthenticatedAdminCasesCaseUidRoute;
  "/admin/slides/$slideUid": typeof AuthenticatedAdminSlidesSlideUidRoute;
  "/admin/system/email": typeof AuthenticatedAdminSystemEmailRoute;
  "/admin/system/monitor": typeof AuthenticatedAdminSystemMonitorRoute;
  "/admin/system/notifications": typeof AuthenticatedAdminSystemNotificationsRoute;
  "/admin/system/queue": typeof AuthenticatedAdminSystemQueueRoute;
  "/admin/system/settings": typeof AuthenticatedAdminSystemSettingsRoute;
  "/admin/tenants/$tenantUid": typeof AuthenticatedAdminTenantsTenantUidRoute;
  "/admin/users/$userUid": typeof AuthenticatedAdminUsersUserUidRoute;
  "/studies/$studyUid/settings": typeof AuthenticatedStudiesStudyUidSettingsRouteWithChildren;
  "/admin/algorithms": typeof AuthenticatedAdminAlgorithmsIndexRoute;
  "/admin/cases": typeof AuthenticatedAdminCasesIndexRoute;
  "/admin/groups": typeof AuthenticatedAdminGroupsIndexRoute;
  "/admin/permissions": typeof AuthenticatedAdminPermissionsIndexRoute;
  "/admin/roles": typeof AuthenticatedAdminRolesIndexRoute;
  "/admin/slides": typeof AuthenticatedAdminSlidesIndexRoute;
  "/admin/studies": typeof AuthenticatedAdminStudiesIndexRoute;
  "/admin/tenants": typeof AuthenticatedAdminTenantsIndexRoute;
  "/admin/users": typeof AuthenticatedAdminUsersIndexRoute;
  "/studies/$studyUid": typeof AuthenticatedStudiesStudyUidIndexRoute;
  "/v/$caseUid": typeof AuthenticatedVCaseUidIndexRoute;
  "/admin/studies/$studyUid/permissions": typeof AuthenticatedAdminStudiesStudyUidPermissionsRoute;
  "/studies/$studyUid/settings/$tab": typeof AuthenticatedStudiesStudyUidSettingsTabRoute;
  "/v/$caseUid/i/$slideUid": typeof AuthenticatedVCaseUidISlideUidRoute;
  "/admin/studies/$studyUid": typeof AuthenticatedAdminStudiesStudyUidIndexRoute;
  "/studies/$studyUid/v/$caseUid": typeof AuthenticatedStudiesStudyUidVCaseUidIndexRoute;
  "/studies/$studyUid/v/$caseUid/i/$slideUid": typeof AuthenticatedStudiesStudyUidVCaseUidISlideUidRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "": typeof AuthenticatedRouteRouteWithChildren;
  "/login": typeof LoginRoute;
  "/privacy": typeof PrivacyRoute;
  "/register": typeof RegisterRoute;
  "/terms": typeof TermsRoute;
  "/account": typeof AuthenticatedAccountRoute;
  "/account/activate": typeof AccountActivateRoute;
  "/account/resend-activation": typeof AccountResendActivationRoute;
  "/account/reset_password": typeof AccountResetpasswordRoute;
  "/i/$slideUid": typeof AuthenticatedISlideUidRoute;
  "/admin": typeof AuthenticatedAdminIndexRoute;
  "/studies": typeof AuthenticatedStudiesIndexRoute;
  "/v": typeof AuthenticatedVIndexRoute;
  "/admin/algorithms/$algorithmId": typeof AuthenticatedAdminAlgorithmsAlgorithmIdRoute;
  "/admin/cases/$caseUid": typeof AuthenticatedAdminCasesCaseUidRoute;
  "/admin/slides/$slideUid": typeof AuthenticatedAdminSlidesSlideUidRoute;
  "/admin/system/email": typeof AuthenticatedAdminSystemEmailRoute;
  "/admin/system/monitor": typeof AuthenticatedAdminSystemMonitorRoute;
  "/admin/system/notifications": typeof AuthenticatedAdminSystemNotificationsRoute;
  "/admin/system/queue": typeof AuthenticatedAdminSystemQueueRoute;
  "/admin/system/settings": typeof AuthenticatedAdminSystemSettingsRoute;
  "/admin/tenants/$tenantUid": typeof AuthenticatedAdminTenantsTenantUidRoute;
  "/admin/users/$userUid": typeof AuthenticatedAdminUsersUserUidRoute;
  "/studies/$studyUid/settings": typeof AuthenticatedStudiesStudyUidSettingsRouteWithChildren;
  "/admin/algorithms": typeof AuthenticatedAdminAlgorithmsIndexRoute;
  "/admin/cases": typeof AuthenticatedAdminCasesIndexRoute;
  "/admin/groups": typeof AuthenticatedAdminGroupsIndexRoute;
  "/admin/permissions": typeof AuthenticatedAdminPermissionsIndexRoute;
  "/admin/roles": typeof AuthenticatedAdminRolesIndexRoute;
  "/admin/slides": typeof AuthenticatedAdminSlidesIndexRoute;
  "/admin/studies": typeof AuthenticatedAdminStudiesIndexRoute;
  "/admin/tenants": typeof AuthenticatedAdminTenantsIndexRoute;
  "/admin/users": typeof AuthenticatedAdminUsersIndexRoute;
  "/studies/$studyUid": typeof AuthenticatedStudiesStudyUidIndexRoute;
  "/v/$caseUid": typeof AuthenticatedVCaseUidIndexRoute;
  "/admin/studies/$studyUid/permissions": typeof AuthenticatedAdminStudiesStudyUidPermissionsRoute;
  "/studies/$studyUid/settings/$tab": typeof AuthenticatedStudiesStudyUidSettingsTabRoute;
  "/v/$caseUid/i/$slideUid": typeof AuthenticatedVCaseUidISlideUidRoute;
  "/admin/studies/$studyUid": typeof AuthenticatedAdminStudiesStudyUidIndexRoute;
  "/studies/$studyUid/v/$caseUid": typeof AuthenticatedStudiesStudyUidVCaseUidIndexRoute;
  "/studies/$studyUid/v/$caseUid/i/$slideUid": typeof AuthenticatedStudiesStudyUidVCaseUidISlideUidRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteRouteWithChildren;
  "/login": typeof LoginRoute;
  "/privacy": typeof PrivacyRoute;
  "/register": typeof RegisterRoute;
  "/terms": typeof TermsRoute;
  "/_authenticated/account": typeof AuthenticatedAccountRoute;
  "/account/activate": typeof AccountActivateRoute;
  "/account/resend-activation": typeof AccountResendActivationRoute;
  "/account/reset_password": typeof AccountResetpasswordRoute;
  "/_authenticated/i/$slideUid": typeof AuthenticatedISlideUidRoute;
  "/_authenticated/admin/": typeof AuthenticatedAdminIndexRoute;
  "/_authenticated/studies/": typeof AuthenticatedStudiesIndexRoute;
  "/_authenticated/v/": typeof AuthenticatedVIndexRoute;
  "/_authenticated/admin/algorithms/$algorithmId": typeof AuthenticatedAdminAlgorithmsAlgorithmIdRoute;
  "/_authenticated/admin/cases/$caseUid": typeof AuthenticatedAdminCasesCaseUidRoute;
  "/_authenticated/admin/slides/$slideUid": typeof AuthenticatedAdminSlidesSlideUidRoute;
  "/_authenticated/admin/system/email": typeof AuthenticatedAdminSystemEmailRoute;
  "/_authenticated/admin/system/monitor": typeof AuthenticatedAdminSystemMonitorRoute;
  "/_authenticated/admin/system/notifications": typeof AuthenticatedAdminSystemNotificationsRoute;
  "/_authenticated/admin/system/queue": typeof AuthenticatedAdminSystemQueueRoute;
  "/_authenticated/admin/system/settings": typeof AuthenticatedAdminSystemSettingsRoute;
  "/_authenticated/admin/tenants/$tenantUid": typeof AuthenticatedAdminTenantsTenantUidRoute;
  "/_authenticated/admin/users/$userUid": typeof AuthenticatedAdminUsersUserUidRoute;
  "/_authenticated/studies/$studyUid/settings": typeof AuthenticatedStudiesStudyUidSettingsRouteWithChildren;
  "/_authenticated/admin/algorithms/": typeof AuthenticatedAdminAlgorithmsIndexRoute;
  "/_authenticated/admin/cases/": typeof AuthenticatedAdminCasesIndexRoute;
  "/_authenticated/admin/groups/": typeof AuthenticatedAdminGroupsIndexRoute;
  "/_authenticated/admin/permissions/": typeof AuthenticatedAdminPermissionsIndexRoute;
  "/_authenticated/admin/roles/": typeof AuthenticatedAdminRolesIndexRoute;
  "/_authenticated/admin/slides/": typeof AuthenticatedAdminSlidesIndexRoute;
  "/_authenticated/admin/studies/": typeof AuthenticatedAdminStudiesIndexRoute;
  "/_authenticated/admin/tenants/": typeof AuthenticatedAdminTenantsIndexRoute;
  "/_authenticated/admin/users/": typeof AuthenticatedAdminUsersIndexRoute;
  "/_authenticated/studies/$studyUid/": typeof AuthenticatedStudiesStudyUidIndexRoute;
  "/_authenticated/v/$caseUid/": typeof AuthenticatedVCaseUidIndexRoute;
  "/_authenticated/admin/studies/$studyUid/permissions": typeof AuthenticatedAdminStudiesStudyUidPermissionsRoute;
  "/_authenticated/studies/$studyUid/settings/$tab": typeof AuthenticatedStudiesStudyUidSettingsTabRoute;
  "/_authenticated/v/$caseUid/i/$slideUid": typeof AuthenticatedVCaseUidISlideUidRoute;
  "/_authenticated/admin/studies/$studyUid/": typeof AuthenticatedAdminStudiesStudyUidIndexRoute;
  "/_authenticated/studies/$studyUid/v/$caseUid/": typeof AuthenticatedStudiesStudyUidVCaseUidIndexRoute;
  "/_authenticated/studies/$studyUid/v/$caseUid/i/$slideUid": typeof AuthenticatedStudiesStudyUidVCaseUidISlideUidRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | ""
    | "/login"
    | "/privacy"
    | "/register"
    | "/terms"
    | "/account"
    | "/account/activate"
    | "/account/resend-activation"
    | "/account/reset_password"
    | "/i/$slideUid"
    | "/admin"
    | "/studies"
    | "/v"
    | "/admin/algorithms/$algorithmId"
    | "/admin/cases/$caseUid"
    | "/admin/slides/$slideUid"
    | "/admin/system/email"
    | "/admin/system/monitor"
    | "/admin/system/notifications"
    | "/admin/system/queue"
    | "/admin/system/settings"
    | "/admin/tenants/$tenantUid"
    | "/admin/users/$userUid"
    | "/studies/$studyUid/settings"
    | "/admin/algorithms"
    | "/admin/cases"
    | "/admin/groups"
    | "/admin/permissions"
    | "/admin/roles"
    | "/admin/slides"
    | "/admin/studies"
    | "/admin/tenants"
    | "/admin/users"
    | "/studies/$studyUid"
    | "/v/$caseUid"
    | "/admin/studies/$studyUid/permissions"
    | "/studies/$studyUid/settings/$tab"
    | "/v/$caseUid/i/$slideUid"
    | "/admin/studies/$studyUid"
    | "/studies/$studyUid/v/$caseUid"
    | "/studies/$studyUid/v/$caseUid/i/$slideUid";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | ""
    | "/login"
    | "/privacy"
    | "/register"
    | "/terms"
    | "/account"
    | "/account/activate"
    | "/account/resend-activation"
    | "/account/reset_password"
    | "/i/$slideUid"
    | "/admin"
    | "/studies"
    | "/v"
    | "/admin/algorithms/$algorithmId"
    | "/admin/cases/$caseUid"
    | "/admin/slides/$slideUid"
    | "/admin/system/email"
    | "/admin/system/monitor"
    | "/admin/system/notifications"
    | "/admin/system/queue"
    | "/admin/system/settings"
    | "/admin/tenants/$tenantUid"
    | "/admin/users/$userUid"
    | "/studies/$studyUid/settings"
    | "/admin/algorithms"
    | "/admin/cases"
    | "/admin/groups"
    | "/admin/permissions"
    | "/admin/roles"
    | "/admin/slides"
    | "/admin/studies"
    | "/admin/tenants"
    | "/admin/users"
    | "/studies/$studyUid"
    | "/v/$caseUid"
    | "/admin/studies/$studyUid/permissions"
    | "/studies/$studyUid/settings/$tab"
    | "/v/$caseUid/i/$slideUid"
    | "/admin/studies/$studyUid"
    | "/studies/$studyUid/v/$caseUid"
    | "/studies/$studyUid/v/$caseUid/i/$slideUid";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/login"
    | "/privacy"
    | "/register"
    | "/terms"
    | "/_authenticated/account"
    | "/account/activate"
    | "/account/resend-activation"
    | "/account/reset_password"
    | "/_authenticated/i/$slideUid"
    | "/_authenticated/admin/"
    | "/_authenticated/studies/"
    | "/_authenticated/v/"
    | "/_authenticated/admin/algorithms/$algorithmId"
    | "/_authenticated/admin/cases/$caseUid"
    | "/_authenticated/admin/slides/$slideUid"
    | "/_authenticated/admin/system/email"
    | "/_authenticated/admin/system/monitor"
    | "/_authenticated/admin/system/notifications"
    | "/_authenticated/admin/system/queue"
    | "/_authenticated/admin/system/settings"
    | "/_authenticated/admin/tenants/$tenantUid"
    | "/_authenticated/admin/users/$userUid"
    | "/_authenticated/studies/$studyUid/settings"
    | "/_authenticated/admin/algorithms/"
    | "/_authenticated/admin/cases/"
    | "/_authenticated/admin/groups/"
    | "/_authenticated/admin/permissions/"
    | "/_authenticated/admin/roles/"
    | "/_authenticated/admin/slides/"
    | "/_authenticated/admin/studies/"
    | "/_authenticated/admin/tenants/"
    | "/_authenticated/admin/users/"
    | "/_authenticated/studies/$studyUid/"
    | "/_authenticated/v/$caseUid/"
    | "/_authenticated/admin/studies/$studyUid/permissions"
    | "/_authenticated/studies/$studyUid/settings/$tab"
    | "/_authenticated/v/$caseUid/i/$slideUid"
    | "/_authenticated/admin/studies/$studyUid/"
    | "/_authenticated/studies/$studyUid/v/$caseUid/"
    | "/_authenticated/studies/$studyUid/v/$caseUid/i/$slideUid";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  PrivacyRoute: typeof PrivacyRoute;
  RegisterRoute: typeof RegisterRoute;
  TermsRoute: typeof TermsRoute;
  AccountActivateRoute: typeof AccountActivateRoute;
  AccountResendActivationRoute: typeof AccountResendActivationRoute;
  AccountResetpasswordRoute: typeof AccountResetpasswordRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  AccountActivateRoute: AccountActivateRoute,
  AccountResendActivationRoute: AccountResendActivationRoute,
  AccountResetpasswordRoute: AccountResetpasswordRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/login",
        "/privacy",
        "/register",
        "/terms",
        "/account/activate",
        "/account/resend-activation",
        "/account/reset_password"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/account",
        "/_authenticated/i/$slideUid",
        "/_authenticated/admin/",
        "/_authenticated/studies/",
        "/_authenticated/v/",
        "/_authenticated/admin/algorithms/$algorithmId",
        "/_authenticated/admin/cases/$caseUid",
        "/_authenticated/admin/slides/$slideUid",
        "/_authenticated/admin/system/email",
        "/_authenticated/admin/system/monitor",
        "/_authenticated/admin/system/notifications",
        "/_authenticated/admin/system/queue",
        "/_authenticated/admin/system/settings",
        "/_authenticated/admin/tenants/$tenantUid",
        "/_authenticated/admin/users/$userUid",
        "/_authenticated/studies/$studyUid/settings",
        "/_authenticated/admin/algorithms/",
        "/_authenticated/admin/cases/",
        "/_authenticated/admin/groups/",
        "/_authenticated/admin/permissions/",
        "/_authenticated/admin/roles/",
        "/_authenticated/admin/slides/",
        "/_authenticated/admin/studies/",
        "/_authenticated/admin/tenants/",
        "/_authenticated/admin/users/",
        "/_authenticated/studies/$studyUid/",
        "/_authenticated/v/$caseUid/",
        "/_authenticated/admin/studies/$studyUid/permissions",
        "/_authenticated/v/$caseUid/i/$slideUid",
        "/_authenticated/admin/studies/$studyUid/",
        "/_authenticated/studies/$studyUid/v/$caseUid/",
        "/_authenticated/studies/$studyUid/v/$caseUid/i/$slideUid"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/terms": {
      "filePath": "terms.tsx"
    },
    "/_authenticated/account": {
      "filePath": "_authenticated/account.tsx",
      "parent": "/_authenticated"
    },
    "/account/activate": {
      "filePath": "account/activate.tsx"
    },
    "/account/resend-activation": {
      "filePath": "account/resend-activation.tsx"
    },
    "/account/reset_password": {
      "filePath": "account/reset_password.tsx"
    },
    "/_authenticated/i/$slideUid": {
      "filePath": "_authenticated/i/$slideUid.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/": {
      "filePath": "_authenticated/admin/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/studies/": {
      "filePath": "_authenticated/studies/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/v/": {
      "filePath": "_authenticated/v/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/algorithms/$algorithmId": {
      "filePath": "_authenticated/admin/algorithms/$algorithmId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/cases/$caseUid": {
      "filePath": "_authenticated/admin/cases/$caseUid.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/slides/$slideUid": {
      "filePath": "_authenticated/admin/slides/$slideUid.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/system/email": {
      "filePath": "_authenticated/admin/system/email.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/system/monitor": {
      "filePath": "_authenticated/admin/system/monitor.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/system/notifications": {
      "filePath": "_authenticated/admin/system/notifications.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/system/queue": {
      "filePath": "_authenticated/admin/system/queue.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/system/settings": {
      "filePath": "_authenticated/admin/system/settings.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/tenants/$tenantUid": {
      "filePath": "_authenticated/admin/tenants/$tenantUid.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/users/$userUid": {
      "filePath": "_authenticated/admin/users/$userUid.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/studies/$studyUid/settings": {
      "filePath": "_authenticated/studies/$studyUid/settings.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/studies/$studyUid/settings/$tab"
      ]
    },
    "/_authenticated/admin/algorithms/": {
      "filePath": "_authenticated/admin/algorithms/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/cases/": {
      "filePath": "_authenticated/admin/cases/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/groups/": {
      "filePath": "_authenticated/admin/groups/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/permissions/": {
      "filePath": "_authenticated/admin/permissions/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/roles/": {
      "filePath": "_authenticated/admin/roles/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/slides/": {
      "filePath": "_authenticated/admin/slides/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/studies/": {
      "filePath": "_authenticated/admin/studies/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/tenants/": {
      "filePath": "_authenticated/admin/tenants/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/users/": {
      "filePath": "_authenticated/admin/users/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/studies/$studyUid/": {
      "filePath": "_authenticated/studies/$studyUid/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/v/$caseUid/": {
      "filePath": "_authenticated/v/$caseUid/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/studies/$studyUid/permissions": {
      "filePath": "_authenticated/admin/studies/$studyUid/permissions.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/studies/$studyUid/settings/$tab": {
      "filePath": "_authenticated/studies/$studyUid/settings.$tab.tsx",
      "parent": "/_authenticated/studies/$studyUid/settings"
    },
    "/_authenticated/v/$caseUid/i/$slideUid": {
      "filePath": "_authenticated/v/$caseUid/i/$slideUid.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/studies/$studyUid/": {
      "filePath": "_authenticated/admin/studies/$studyUid/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/studies/$studyUid/v/$caseUid/": {
      "filePath": "_authenticated/studies/$studyUid/v/$caseUid/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/studies/$studyUid/v/$caseUid/i/$slideUid": {
      "filePath": "_authenticated/studies/$studyUid/v/$caseUid/i/$slideUid.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
