trainer:
  class_path: eva.Trainer
  init_args:
    accelerator: gpu
    devices: 1 # multi-gpu training is not officially supported, so will set to 1 for now
    n_runs: &N_RUNS ${oc.env:N_RUNS, 1}
    default_root_dir: &OUTPUT_ROOT ${oc.env:OUTPUT_ROOT, /projects/mri_fomo/eva/logs/${oc.env:MODEL_NAME, mri_vits14_no_pretrain_v3}/classification/${oc.env:DATASET_NAME, duke}/${oc.env:LABEL_NAME, scanner_model}/mil/single}
    max_epochs: &MAX_EPOCHS ${oc.env:MAX_EPOCHS, 1}
    callbacks:
      - class_path: eva.callbacks.ConfigurationLogger
      - class_path: lightning.pytorch.callbacks.TQDMProgressBar
        init_args:
          refresh_rate: ${oc.env:TQDM_REFRESH_RATE, 10}
      - class_path: lightning.pytorch.callbacks.LearningRateMonitor
        init_args:
          logging_interval: epoch
      - class_path: lightning.pytorch.callbacks.ModelCheckpoint
        init_args:
          filename: best
          save_last: true
          save_top_k: 1
          monitor: &MONITOR_METRIC ${oc.env:MONITOR_METRIC, val/AverageLoss}
          mode: &MONITOR_METRIC_MODE ${oc.env:MONITOR_METRIC_MODE, min}
      - class_path: lightning.pytorch.callbacks.EarlyStopping
        init_args:
          min_delta: 0
          patience: 100
          monitor: *MONITOR_METRIC
          mode: *MONITOR_METRIC_MODE
      - class_path: eva.callbacks.ClassificationEmbeddingsWriter
        init_args:
          output_dir: &DATASET_EMBEDDINGS_ROOT ${oc.env:EMBEDDINGS_ROOT, /projects/mri_fomo/eva/embeddings}/${oc.env:MODEL_NAME, mri_vits14_no_pretrain_v3}/classification/${oc.env:DATASET_NAME, duke}/${oc.env:LABEL_NAME, scanner_model}/mil/single
          dataloader_idx_map:
            0: train
            1: val
            2: test
          metadata_keys: ["multi_id", "slice_index", "patient_id"]
          overwrite: True
          backbone:
            class_path: fef.models.networks.backbones.mri_dinov2.DINOv2VIT
            init_args:
              checkpoint_path: /projects/mri_fomo/training_outputs/${oc.env:CHECKPOINT_PATH, mri_vits14_no_pretrain_v3/eval/training_249999}/teacher_checkpoint.pth
              timm_ckpt: /projects/mri_fomo/eva/timm_checkpoints/${oc.env:CHECKPOINT_PATH, mri_vits14_no_pretrain_v3/eval/training_249999}/teacher_checkpoint.pth
              out_indices: ${oc.env:OUT_INDICES, 1}
              output_tokens: cls
              model_kwargs:
                dynamic_img_size: true
                embed_dim: 384 # for vitbase 768, for small 384. to do: make this more flexible
    logger:
      - class_path: lightning.pytorch.loggers.TensorBoardLogger
        init_args:
          save_dir: *OUTPUT_ROOT
          name: ""
model:
  class_path: eva.HeadModule
  init_args:
    head:
      class_path: eva.vision.models.networks.ABMIL
      init_args:
        input_size: ${oc.env:IN_FEATURES, 384}
        output_size: &NUM_CLASSES ${oc.env:NUM_CLASSES, 6}
        projected_input_size: 128
        hidden_size_attention: 64
        hidden_sizes_mlp: [64, 32]
        dropout_input_embeddings: 0.2
        dropout_attention: 0.3
        dropout_mlp: 0.3
    criterion: torch.nn.CrossEntropyLoss
    optimizer:
      class_path: torch.optim.AdamW
      # init_args:
      #   lr: ${oc.env:LR_VALUE, 1.0e-04}
      # weight_decay: 0.01
    lr_scheduler:
      class_path: torch.optim.lr_scheduler.CyclicLR # Changed from PolynomialLR
      init_args:
        base_lr: 0.00001
        max_lr: 0.0001
        step_size_up: 35000
        cycle_momentum: false
        mode: 'triangular2'
    # postprocess:
    #   predictions_transforms:
    #     - class_path: torch.argmax
    #       init_args:
    #         dim: 1

    metrics:
      common:
        - class_path: eva.metrics.AverageLoss
        - class_path: eva.metrics.MulticlassClassificationMetrics
          init_args:
            num_classes: *NUM_CLASSES
            average: "macro"
            # evaluation:
            #   - class_path: torchmetrics.ClasswiseWrapper
            #     init_args:
            #       metric:
            #         class_path: torchmetrics.classification.MulticlassAccuracy
            #         init_args:
            #           num_classes: *NUM_CLASSES
            #           average: "none"
data:
  class_path: eva.DataModule
  init_args:
    datasets:
      train:
        class_path: eva.datasets.MultiEmbeddingsClassificationDataset
        init_args: &DATASET_ARGS
          root: *DATASET_EMBEDDINGS_ROOT
          manifest_file: manifest.csv
          column_mapping: {"path": "embeddings", "target": "target", "split": "split", "multi_id": "multi_id", "slice_index": "slice_index"}
          split: train
          # embeddings_transforms:
          #   class_path: fef.mri.transforms.reshape.ReshapeTo2D
          # Or use a PyTorch transform
          # class_path: torchvision.transforms.v2.Lambda
          # init_args:
          #   lambd: "lambda x: x.reshape(-1, x.shape[-1]) if x.ndim > 2 else x"
          target_transforms:
            class_path: fef.transforms.dtype.ArrayToLongTensor
      val:
        class_path: eva.datasets.MultiEmbeddingsClassificationDataset
        init_args:
          !!merge <<: *DATASET_ARGS
          split: val
      test:
        class_path: eva.datasets.MultiEmbeddingsClassificationDataset
        init_args:
          !!merge <<: *DATASET_ARGS
          split: test
      predict:
        - class_path: fef.datasets.classification.mri.mri_cls_datasets_singlescan.MRIMILClassificationDataset
          init_args: &PREDICT_DATASET_ARGS
            label_file: ${oc.env:LABEL_FILE, /data/groups/public/archive/MAMA-MIA/manifests/manifest_duke.csv}
            label_name: ${oc.env:LABEL_NAME, scanner_model}
            split: train
            crop_percentile: ${oc.env:CROP_PERCENTILE, 85.0}
            visualize_preprocessing: ${oc.env:VISUALIZE, False}
            tumor_ratio: ${oc.env:TUMOR_RATIO, null}
            min_class_percentage: ${oc.env:MIN_CLASS_PERCENTAGE, 5}
            image_transforms:
              class_path: torchvision.transforms.v2.Compose
              init_args:
                transforms:
                  - class_path: fef.transforms.transforms.PercentileClipper
                    init_args:
                      percentile: 99.9
                  - class_path: fef.transforms.transforms.MinMaxNormalizer
                  - class_path: torchvision.transforms.v2.Normalize
                    init_args:
                      mean: [0.1008]
                      std: [0.193391]
                  - class_path: fef.transforms.cropping.PatchDivisiblePadder
                    init_args:
                      patch_size: ${oc.env:PATCH_SIZE, 14}
        - class_path: fef.datasets.classification.mri.mri_cls_datasets_singlescan.MRIMILClassificationDataset
          init_args:
            !!merge <<: *PREDICT_DATASET_ARGS
            split: val
        - class_path: fef.datasets.classification.mri.mri_cls_datasets_singlescan.MRIMILClassificationDataset
          init_args:
            !!merge <<: *PREDICT_DATASET_ARGS
            split: test
    dataloaders:
      train:
        batch_size: &BATCH_SIZE ${oc.env:BATCH_SIZE, 1}
        pin_memory: true
        shuffle: true
        num_workers: 4
      val:
        batch_size: *BATCH_SIZE
        pin_memory: true
        num_workers: 4
      test:
        batch_size: *BATCH_SIZE
        pin_memory: true
        num_workers: 4
      predict:
        batch_size: &PREDICT_BATCH_SIZE ${oc.env:PREDICT_BATCH_SIZE, 1}
        pin_memory: true
        num_workers: 4
