# Copyright 2024 AI for Oncology Research Group. All Rights Reserved.
# Copyright 2024 Jonas Teuwen. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from typing import Any

import pyvips

Dimensions = tuple[int, int]
Spacing = tuple[float, float]

class AbstractSlideBackend:
    def __init__(self, filename: str) -> None: ...
    def get_best_level_for_downsample(self, arg0: float) -> int: ...
    def set_spacing(self, arg0: tuple[float, float]) -> None: ...
    @property
    def dimensions(self) -> tuple[int, int]: ...
    @property
    def level_count(self) -> int: ...
    @property
    def level_dimensions(self) -> tuple[Dimensions]: ...
    @property
    def level_downsamples(self) -> tuple[Dimensions]: ...
    @property
    def level_spacings(self) -> tuple[Spacing]: ...
    @property
    def magnification(self) -> float | None: ...
    @property
    def spacing(self) -> Spacing: ...
    @property
    def vendor(self) -> str | None: ...
    def close(self) -> None: ...

class VImageWrapper:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get_image(self) -> Any: ...

class VipsSlide(AbstractSlideBackend):
    def __init__(
        self, filename: str, load_with_openslide: bool = ..., rgb: bool = ..., apply_color_profile: bool = ...
    ) -> None: ...
    def get_thumbnail(self, size: tuple[int, int]) -> pyvips.Image: ...
    def read_region(self, coordinates: tuple[int, int], level: int, size: tuple[int, int]) -> pyvips.Image: ...
    @property
    def spacing(self) -> tuple[float, float]: ...
