load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "errors",
    srcs = [
        "auth_errors.go",
        "errors.go",
        "mask_errors.go",
        "slide_errors.go",
    ],
    importpath = "aifo.dev/aifo/slidescope/internal/server/errors",
    visibility = ["//visibility:public"],
)
