load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "sqlite",
    srcs = [
        "algorithms_methods.go",
        "annotations_methods.go",
        "base.go",
        "cases_methods.go",
        "image_types_methods.go",
        "notifications_methods.go",
        "settings_methods.go",
        "slides_methods.go",
        "studies_methods.go",
        "tenants_methods.go",
        "users_methods.go",
    ],
    importpath = "aifo.dev/aifo/slideinsight/internal/datasources/database/sqlite",
    visibility = ["//aifo/slideinsight:__subpackages__"],
    deps = [
        "//aifo/slideinsight/internal/datasources/database/sqlite/algorithms",
        "//aifo/slideinsight/internal/datasources/database/sqlite/annotations",
        "//aifo/slideinsight/internal/datasources/database/sqlite/cases",
        "//aifo/slideinsight/internal/datasources/database/sqlite/email_templates",
        "//aifo/slideinsight/internal/datasources/database/sqlite/image_types",
        "//aifo/slideinsight/internal/datasources/database/sqlite/notifications",
        "//aifo/slideinsight/internal/datasources/database/sqlite/rbac",
        "//aifo/slideinsight/internal/datasources/database/sqlite/regions",
        "//aifo/slideinsight/internal/datasources/database/sqlite/schema",
        "//aifo/slideinsight/internal/datasources/database/sqlite/settings",
        "//aifo/slideinsight/internal/datasources/database/sqlite/slides",
        "//aifo/slideinsight/internal/datasources/database/sqlite/studies",
        "//aifo/slideinsight/internal/datasources/database/sqlite/tenants",
        "//aifo/slideinsight/internal/datasources/database/sqlite/users",
        "//aifo/slideinsight/internal/server/domain",
        "//aifo/slideinsight/internal/server/errors",
        "//aifo/slideinsight/internal/server/ports",
        "//aifo/slideinsight/internal/utils",
        "@com_github_gofiber_fiber_v2//log",
        "@com_github_google_uuid//:uuid",
        "@com_github_mattn_go_sqlite3//:go-sqlite3",
    ],
)
