load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "handlers",
    srcs = [
        "algorithms.go",
        "auth.go",
        "cases.go",
        "email_templates.go",
        "groups.go",
        "image_types.go",
        "notifications.go",
        "objectgrants.go",
        "params.go",
        "permissions.go",
        "raster_annotations.go",
        "regions.go",
        "roles.go",
        "settings.go",
        "slides.go",
        "studies.go",
        "system.go",
        "system_monitor.go",
        "tenants.go",
        "users.go",
        "utils.go",
        "vector_annotations.go",
    ],
    importpath = "aifo.dev/aifo/slideinsight/internal/server/handlers",
    visibility = ["//aifo/slideinsight:__subpackages__"],
    deps = [
        "//aifo/slideinsight/internal/config",
        "//aifo/slideinsight/internal/queue",
        "//aifo/slideinsight/internal/server/auth",
        "//aifo/slideinsight/internal/server/domain",
        "//aifo/slideinsight/internal/server/email",
        "//aifo/slideinsight/internal/server/errors",
        "//aifo/slideinsight/internal/server/middleware",
        "//aifo/slideinsight/internal/server/notifications",
        "//aifo/slideinsight/internal/server/ports",
        "//aifo/slideinsight/internal/server/services",
        "//aifo/slideinsight/internal/server/services/auth",
        "//aifo/slideinsight/internal/server/validation",
        "//aifo/slideinsight/internal/utils",
        "@com_github_gofiber_contrib_websocket//:websocket",
        "@com_github_gofiber_fiber_v2//:fiber",
        "@com_github_gofiber_fiber_v2//log",
        "@com_github_shirou_gopsutil_v4//cpu",
        "@com_github_shirou_gopsutil_v4//disk",
        "@com_github_shirou_gopsutil_v4//load",
        "@com_github_shirou_gopsutil_v4//mem",
        "@com_github_shirou_gopsutil_v4//net",
        "@com_github_shirou_gopsutil_v4//process",
        "@org_golang_x_crypto//bcrypt",
        "@org_uber_go_zap//:zap",
    ],
)
