load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_go//go:def.bzl", "go_library", "go_test")

cc_library(
    name = "tiff_wrapper",
    srcs = ["libtiff_wrapper.c"],
    hdrs = ["libtiff_wrapper.h"],
    includes = ["."],
    visibility = ["//visibility:private"],
    deps = ["@libtiff"],
)

go_library(
    name = "tiff",
    srcs = [
        "libtiff_wrapper.c",
        "libtiff_wrapper.h",
        "tiff.go",
    ],
    cdeps = [":tiff_wrapper"],
    cgo = True,
    importpath = "aifo.dev/aifo/slidescope/internal/tiff",
    visibility = ["//visibility:public"],
)

go_test(
    name = "tiff_test",
    srcs = ["tiff_test.go"],
    data = glob(["testdata/**"]),
    embed = [":tiff"],
)
