load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "datasources",
    srcs = ["data_sources.go"],
    importpath = "aifo.dev/aifo/slidescope/internal/datasources",
    visibility = ["//visibility:public"],
    deps = [
        "//aifo/slidescope/internal/datasources/database",
    ],
)
