load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "routes",
    srcs = [
        "services.go",
        "setup.go",
    ],
    importpath = "aifo.dev/aifo/slideinsight/internal/server/routes",
    visibility = ["//aifo/slideinsight:__subpackages__"],
    deps = [
        "//aifo/slideinsight/internal/config",
        "//aifo/slideinsight/internal/queue",
        "//aifo/slideinsight/internal/server/email",
        "//aifo/slideinsight/internal/server/handlers",
        "//aifo/slideinsight/internal/server/middleware",
        "//aifo/slideinsight/internal/server/ports",
        "//aifo/slideinsight/internal/server/ratelimit",
        "//aifo/slideinsight/internal/server/routes/algorithms",
        "//aifo/slideinsight/internal/server/routes/annotations",
        "//aifo/slideinsight/internal/server/routes/auth",
        "//aifo/slideinsight/internal/server/routes/cases",
        "//aifo/slideinsight/internal/server/routes/groups",
        "//aifo/slideinsight/internal/server/routes/notifications",
        "//aifo/slideinsight/internal/server/routes/objectgrants",
        "//aifo/slideinsight/internal/server/routes/permissions",
        "//aifo/slideinsight/internal/server/routes/regions",
        "//aifo/slideinsight/internal/server/routes/roles",
        "//aifo/slideinsight/internal/server/routes/settings",
        "//aifo/slideinsight/internal/server/routes/slides",
        "//aifo/slideinsight/internal/server/routes/studies",
        "//aifo/slideinsight/internal/server/routes/system",
        "//aifo/slideinsight/internal/server/routes/tenants",
        "//aifo/slideinsight/internal/server/routes/users",
        "//aifo/slideinsight/internal/server/services",
        "//aifo/slideinsight/internal/server/services/auth",
        "@com_github_gofiber_fiber_v2//:fiber",
        "@com_github_gofiber_fiber_v2//middleware/compress",
    ],
)
