load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "auth",
    srcs = ["password.go"],
    importpath = "aifo.dev/aifo/slidescope/internal/server/auth",
    visibility = ["//visibility:public"],
    deps = [
        "@org_golang_x_crypto//bcrypt",
    ],
)

go_test(
    name = "auth_test",
    srcs = ["password_test.go"],
    embed = [":auth"],
    deps = [
        "@org_golang_x_crypto//bcrypt",
    ],
)
