load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "image_types",
    srcs = [
        "adapter.go",
    ],
    importpath = "aifo.dev/aifo/slideinsight/internal/datasources/database/sqlite/image_types",
    visibility = ["//aifo/slideinsight:__subpackages__"],
    deps = [
        "//aifo/slideinsight/internal/server/ports",
        "//aifo/slideinsight/internal/utils",
        "@com_github_mattn_go_sqlite3//:go-sqlite3",
    ],
)
