load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "services",
    srcs = [
        "algorithms.go",
        "application.go",
        "base.go",
        "base_pagination.go",
        "cases.go",
        "conversion_helpers.go",
        "email.go",
        "email_templates.go",
        "groups.go",
        "image_types.go",
        "notifications.go",
        "objectgrants.go",
        "permissions.go",
        "raster_annotations.go",
        "regions.go",
        "roles.go",
        "settings.go",
        "shared_permissions.go",
        # "slide_cache.go",
        "slides.go",
        "studies.go",
        "tenant_filter.go",
        "tenants.go",
        "users.go",
        "vector_annotations.go",
    ],
    importpath = "aifo.dev/aifo/slideinsight/internal/server/services",
    visibility = ["//aifo/slideinsight:__subpackages__"],
    deps = [
        "//aifo/openslide_go/openslide",
        "//aifo/slideinsight/internal/config",
        "//aifo/slideinsight/internal/datasources/database",
        "//aifo/slideinsight/internal/server/auth",
        "//aifo/slideinsight/internal/server/domain",
        "//aifo/slideinsight/internal/server/errors",
        "//aifo/slideinsight/internal/server/middleware",
        "//aifo/slideinsight/internal/server/ports",
        "//aifo/slideinsight/internal/server/services/auth",
        "//aifo/slideinsight/internal/server/services/slides",
        "//aifo/slideinsight/internal/slides",
        "//aifo/slideinsight/internal/tiff",
        "//aifo/slideinsight/internal/utils",
        "@com_github_aws_aws_sdk_go_v2//aws",
        "@com_github_aws_aws_sdk_go_v2_config//:config",
        "@com_github_aws_aws_sdk_go_v2_service_ses//:ses",
        "@com_github_aws_aws_sdk_go_v2_service_ses//types",
        "@com_github_gofiber_contrib_websocket//:websocket",
        "@com_github_gofiber_fiber_v2//:fiber",
        "@com_github_gofiber_fiber_v2//log",
        "@com_github_golang_jwt_jwt_v5//:jwt",
        "@com_github_google_uuid//:uuid",
        "@org_golang_x_crypto//bcrypt",
        "@org_uber_go_zap//:zap",
    ],
)

go_test(
    name = "permission_integration_test",
    srcs = ["permission_integration_test.go"],
    embed = [":services"],
    deps = [
        "//aifo/slideinsight/internal/server/ports",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//mock",
    ],
)
