load("@rules_go//go:def.bzl", "go_binary", "go_library")

exports_files([
    "main.go",
])

go_library(
    name = "slidescope_lib",
    srcs = ["main.go"],
    importpath = "aifo.dev/aifo/slidescope/cmd/slidescope",
    visibility = ["//aifo/slidescope:__pkg__"],
    deps = [
        "//aifo/slidescope/internal/config",
        "//aifo/slidescope/internal/datasources",
        "//aifo/slidescope/internal/datasources/database",
        "//aifo/slidescope/internal/server",
    ],
)

go_binary(
    name = "slidescope",
    embed = [":slidescope_lib"],
    visibility = ["//visibility:public"],
)
