load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@pip//:requirements.bzl", "requirement")

py_binary(
    name = "compare_backends",
    srcs = ["compare_backends.py"],
    deps = [
        "//aifo/dlup",
        "@rules_python//python/runfiles",
        requirement("tqdm"),
    ],
)

py_binary(
    name = "cpp_python_wrapper_dataset",
    srcs = ["cpp_python_wrapper_dataset.py"],
    deps = ["//aifo/dlup"],
)

py_binary(
    name = "create_circular_roi",
    srcs = ["create_circular_roi.py"],
    deps = ["//aifo/dlup"],
)

py_binary(
    name = "darwin_to_dlup_xml_simple",
    srcs = ["darwin_to_dlup_xml_simple.py"],
    deps = ["//aifo/dlup"],
)

py_binary(
    name = "annotations_to_mask",
    srcs = ["annotations_to_mask.py"],
    data = [
        "files/dlup_annotation_test.xml",
    ],
    visibility = ["//visibility:public"],
    deps = [
        requirement("pillow"),
        "//aifo/dlup",
    ],
)

py_binary(
    name = "resample_image_to_tiff",
    srcs = ["resample_image_to_tiff.py"],
    visibility = ["//visibility:public"],
    deps = ["//aifo/dlup"],
)
