load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "database",
    srcs = [
        "db.go",
        "db_mock.go",
        "sqlite_db.go",
    ],
    importpath = "aifo.dev/aifo/slidescope/internal/datasources/database",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_mattn_go_sqlite3//:go-sqlite3",
        "@com_github_stretchr_testify//mock",
    ],
)

go_test(
    name = "database_test",
    srcs = [
        "db_test.go",
        "sqlite_db_test.go",
    ],
    embed = [":database"],
    deps = [
        "@com_github_mattn_go_sqlite3//:go-sqlite3",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)

go_test(
    name = "database_sqlite_test",
    srcs = [
        "sqlite_db_test.go",
    ],
    embed = [":database"],
    deps = [
        "@com_github_mattn_go_sqlite3//:go-sqlite3",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
