load("@rules_go//go:def.bzl", "go_library", "go_test")

filegroup(
    name = "openapi_yaml",
    srcs = ["public/openapi.yaml"],
    visibility = ["//visibility:private"],
)

go_library(
    name = "server",
    srcs = ["server.go"],
    embedsrcs = [
        ":openapi_yaml",
    ],
    importpath = "aifo.dev/aifo/slidescope/internal/server",
    visibility = ["//visibility:public"],
    deps = [
        "//aifo/slidescope/internal/config",
        "//aifo/slidescope/internal/datasources",
        "//aifo/slidescope/internal/server/handlers",
        "//aifo/slidescope/internal/server/middleware",
        "//aifo/slidescope/internal/server/services",
        "//aifo/slidescope/ui:ui_lib",
        "@com_github_gofiber_fiber_v2//:fiber",
        "@com_github_gofiber_fiber_v2//middleware/cors",
        "@com_github_gofiber_fiber_v2//middleware/filesystem",
        "@com_github_gofiber_fiber_v2//middleware/requestid",
        "@com_github_golang_jwt_jwt_v5//:jwt",
    ],
)
