from typing import ClassVar, Iterator, Union, overload

C: GridOrder
F: GridOrder
overflow: TilingMode
skip: TilingMode

_SizeType = Union[tuple[Union[int, float], Union[int, float]], int, float]

class Grid:
    def __init__(self, coordinates: list[_SizeType], order: Union[GridOrder, str] = ...) -> None: ...
    @staticmethod
    def from_tiling(
        offset: _SizeType,
        size: _SizeType,
        tile_size: _SizeType,
        tile_overlap: _SizeType = ...,
        mode: Union[TilingMode, str] = ...,
        order: Union[GridOrder, str] = ...,
    ) -> Grid: ...
    @overload
    def __getitem__(self, arg0: int) -> _SizeType: ...
    @overload
    def __getitem__(self, arg0: slice) -> list[_SizeType]: ...
    def __iter__(self) -> Iterator[_SizeType]: ...
    def __len__(self) -> int: ...
    @property
    def order(self) -> GridOrder: ...
    @property
    def size(self) -> _SizeType: ...

class GridOrder:
    __members__: ClassVar[dict[str, "GridOrder"]]  # read-only
    C: ClassVar["GridOrder"]
    F: ClassVar["GridOrder"]
    __entries: ClassVar[dict[str, "GridOrder"]]

    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class TilingMode:
    __members__: ClassVar[dict[str, "TilingMode"]]  # read-only
    __entries: ClassVar[dict[str, "TilingMode"]]
    overflow: ClassVar["TilingMode"]
    skip: ClassVar["TilingMode"]

    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

def tiles_grid_coordinates(
    size: _SizeType, tile_size: _SizeType, tile_overlap: _SizeType = ..., mode: Union[TilingMode, str] = ...
) -> list[_SizeType]: ...
