load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "domain",
    srcs = [
        "auth.go",
        "errors.go",
        "masks.go",
        "slides.go",
        "users.go",
    ],
    importpath = "aifo.dev/aifo/slidescope/internal/server/domain",
    visibility = ["//visibility:public"],
)
