load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "cases",
    srcs = [
        "adapter.go",
        "crud.go",
        "queries.go",
        "search.go",
        "study_relations.go",
    ],
    importpath = "aifo.dev/aifo/slideinsight/internal/datasources/database/sqlite/cases",
    visibility = ["//aifo/slideinsight:__subpackages__"],
    deps = [
        "//aifo/slideinsight/internal/server/ports",
        "//aifo/slideinsight/internal/utils",
        "@com_github_gofiber_fiber_v2//log",
    ],
)
