load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "queue",
    srcs = [
        "algorithm_task.go",
        "email_task.go",
        "manager.go",
        "queue.go",
    ],
    importpath = "aifo.dev/aifo/slideinsight/internal/queue",
    visibility = ["//aifo/slideinsight:__subpackages__"],
    deps = [
        "//aifo/slideinsight/internal/server/ports",
        "@com_github_gofiber_fiber_v2//log",
        "@org_uber_go_ratelimit//:ratelimit",
    ],
)
